// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type Session struct {
	ID        string
	UserID    int32
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	DisplayName  string
	Role         string
	Active       bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
